---
- name: Build HTML
  hosts: all
  gather_facts: no
  become: yes
  vars:
    num_services: 10
  tasks:
    - name: Build HTML
      template:
        src: "{{ playbook_dir }}/index2.html.j2"
        dest: /usr/share/nginx/html/index.html
