---
- name: Build Docker Compose File
  hosts: all
  gather_facts: no
  tasks:
    - name: Build Docker Compose File
      template:
        src: "{{ playbook_dir }}/docker-compose.j2"
        dest: /home/ec2-user/docker-compose.yml
