version: '3'
services:
  web0:
    image: pxdlab:latest
    ports:
      - "8880:8888"
  web1:
    image: pxdlab:latest
    ports:
      - "8881:8888"
  web2:
    image: pxdlab:latest
    ports:
      - "8882:8888"
