version: '3'
services:
  web:
    entrypoint:
      - "git clone https://github.com/avigailvantu/Open-Demolitions.git"
      - "cd Open-Demolitions"
      - "rm -rf .git"
      - "cd data:analysis"
      - "jupyter notebook"
    image: eakman/pxdlab2
    ports:
      - "8880:8888"
    deploy:
      resources:
        limits:
          cpus: "0.25"
          memory: "1"
        reservations:
          cpus: "0.25"
          memory: "1"
